
HOST=http://localhost:8080

MOVIE-URL=https://api.themoviedb.org/3

TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4ODJhNTI2MjljZDQyYjJjZWVmNTM5ODcyMGQxYjNkMCIsInN1YiI6IjY2MzUyYzcwMzU4ZGE3MDEyZDU1NTlhNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.6c6LRHSRomkGljCbajnsJRYsEkFYl2SvpYrtXv2cjtw
            
BASIC-LOGIN=test
BASIC-PASSWORD=mypass123